package com.chatchat.chat.conversation.service;

import com.chatchat.chat.conversation.store.ChatMessageDetailStore;

import com.chatchat.chat.conversation.persistence.ChatMessageIndexRepository;

import com.chatchat.chat.conversation.persistence.ChatMessageIndexEntity;

import com.chatchat.chat.conversation.persistence.ConversationSummaryRepository;

import com.chatchat.chat.conversation.persistence.ChatSessionRepository;

import com.chatchat.chat.conversation.persistence.ChatSessionEntity;

import com.chatchat.chat.conversation.service.ConversationService;

import com.chatchat.chat.conversation.model.ChatMessageDetail;

import com.chatchat.chat.conversation.model.Conversation;

import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class ConversationServiceResultDeduplicationTest {

    @Test
    void keepsTheRicherOfTwoAdjacentEquivalentAssistantResults() {
        Conversation.Message user = Conversation.Message.builder()
            .id("user-1")
            .role("user")
            .content("分析最新融资融券数据")
            .build();
        Conversation.Message richAnswer = Conversation.Message.builder()
            .id("assistant-runtime")
            .role("assistant")
            .content("## 分析结论\n\n融资余额上升。")
            .steps(List.of(Map.of("type", "TOOL_RESULT")))
            .traces(List.of(Map.of("toolName", "margin_query")))
            .visualizationSpec(Map.of("type", "table"))
            .taskId("task-1")
            .build();
        Conversation.Message plainDuplicate = Conversation.Message.builder()
            .id("assistant-memory")
            .role("assistant")
            .content("## 分析结论\n融资余额上升。")
            .build();

        List<Conversation.Message> result = ConversationService.collapseDuplicateAssistantResults(
            List.of(user, richAnswer, plainDuplicate)
        );

        assertThat(result).containsExactly(user, richAnswer);
    }

    @Test
    void doesNotCollapseAssistantResultsSeparatedByAUserTurn() {
        Conversation.Message answer1 = message("assistant-1", "assistant", "相同回答");
        Conversation.Message user = message("user-2", "user", "请再确认一次");
        Conversation.Message answer2 = message("assistant-2", "assistant", "相同回答");

        assertThat(ConversationService.collapseDuplicateAssistantResults(List.of(answer1, user, answer2)))
            .containsExactly(answer1, user, answer2);
    }

    @Test
    void collapsesRuntimeAndMemoryCopiesWhenTheirNormalizedAnswersDiffer() {
        Conversation.Message memoryAnswer = Conversation.Message.builder()
            .id("assistant-memory")
            .role("assistant")
            .content("Answer generated by the memory writer")
            .traces(List.of(Map.of("toolName", "metadata_query")))
            .build();
        Conversation.Message runtimeAnswer = Conversation.Message.builder()
            .id("assistant-runtime")
            .role("assistant")
            .content("Answer normalized for the runtime UI")
            .steps(List.of(Map.of("type", "TOOL_RESULT"), Map.of("type", "MODEL_RESULT")))
            .taskId("task-1")
            .build();

        assertThat(ConversationService.collapseDuplicateAssistantResults(List.of(memoryAnswer, runtimeAnswer)))
            .containsExactly(runtimeAnswer);
    }

    @Test
    void doesNotCollapseTwoDistinctRuntimeResults() {
        Conversation.Message first = Conversation.Message.builder()
            .id("assistant-1")
            .role("assistant")
            .content("First result")
            .taskId("task-1")
            .build();
        Conversation.Message second = Conversation.Message.builder()
            .id("assistant-2")
            .role("assistant")
            .content("Second result")
            .taskId("task-2")
            .build();

        assertThat(ConversationService.collapseDuplicateAssistantResults(List.of(first, second)))
            .containsExactly(first, second);
    }

    @Test
    void collapsesTwoCopiesFromTheSameTaskWhenBothCarryTheTaskId() {
        Conversation.Message plainCopy = Conversation.Message.builder()
            .id("assistant-history")
            .role("assistant")
            .content("Plain persisted answer")
            .uiResponse(Map.of("answer", "Plain persisted answer"))
            .taskId("task-1")
            .build();
        Conversation.Message runtimeCopy = Conversation.Message.builder()
            .id("assistant-runtime")
            .role("assistant")
            .content("Rich runtime answer")
            .uiResponse(Map.of("answer", "Rich runtime answer"))
            .steps(List.of(Map.of("type", "TOOL_RESULT")))
            .taskId("task-1")
            .build();

        assertThat(ConversationService.collapseDuplicateAssistantResults(List.of(plainCopy, runtimeCopy)))
            .containsExactly(runtimeCopy);
    }

    @Test
    void collapsesCopiesWhoseUiAnswersDifferButRawContentMatches() {
        Conversation.Message artifactCopy = Conversation.Message.builder()
            .id("assistant-artifact")
            .role("assistant")
            .content("## Customer analysis\n\nThe complete answer")
            .uiResponse(Map.of("answer", "Artifact preview"))
            .build();
        Conversation.Message runtimeCopy = Conversation.Message.builder()
            .id("assistant-runtime")
            .role("assistant")
            .content("## Customer analysis The complete answer")
            .uiResponse(Map.of("answer", "Runtime presentation"))
            .steps(List.of(Map.of("type", "MODEL_RESULT")))
            .build();

        assertThat(ConversationService.collapseDuplicateAssistantResults(List.of(artifactCopy, runtimeCopy)))
            .containsExactly(runtimeCopy);
    }

    @Test
    void conversationDetailCollapsesAlreadyPersistedRuntimeAndMemoryCopies() {
        ChatSessionRepository sessions = mock(ChatSessionRepository.class);
        ChatMessageIndexRepository indexes = mock(ChatMessageIndexRepository.class);
        ConversationSummaryRepository summaries = mock(ConversationSummaryRepository.class);
        ChatMessageDetailStore details = mock(ChatMessageDetailStore.class);
        ConversationService service = new ConversationService(sessions, indexes, summaries, details);

        ChatSessionEntity session = new ChatSessionEntity();
        session.setSessionId("conversation-1");
        session.setTenantId("tenant-1");
        session.setUserId("user-1");
        session.setTitle("客户交易分析");
        session.setStatus("completed");
        session.setCreatedAt(Instant.parse("2026-07-31T01:00:00Z"));
        session.setUpdatedAt(Instant.parse("2026-07-31T01:01:00Z"));

        ChatMessageIndexEntity userIndex = index("user-1", "user", "key-user", Instant.parse("2026-07-31T01:00:00Z"));
        ChatMessageIndexEntity memoryIndex = index("assistant-memory", "assistant", "key-memory", Instant.parse("2026-07-31T01:00:01Z"));
        ChatMessageIndexEntity runtimeIndex = index("assistant-runtime", "assistant", "key-runtime", Instant.parse("2026-07-31T01:00:02Z"));
        Map<String, ChatMessageDetail> stored = new LinkedHashMap<>();
        stored.put("key-user", detail("user-1", "user", "分析客户 070200046604", null));
        String answer = "完整的客户交易分析报告 [evidence: tool://api_template_execute#result=3/child=1]。";
        stored.put("key-memory", detail("assistant-memory", "assistant", answer, null));
        stored.put("key-runtime", detail("assistant-runtime", "assistant", answer, "task-1"));

        when(sessions.findBySessionIdAndTenantId("conversation-1", "tenant-1"))
            .thenReturn(Optional.of(session));
        when(indexes.findByTenantIdAndSessionIdOrderByCreatedAtAsc("tenant-1", "conversation-1"))
            .thenReturn(List.of(userIndex, memoryIndex, runtimeIndex));
        when(details.getAll(List.of("key-user", "key-memory", "key-runtime"))).thenReturn(stored);

        Conversation conversation = service.getConversation("tenant-1", "conversation-1").orElseThrow();

        assertThat(conversation.getMessages())
            .extracting(Conversation.Message::getId)
            .containsExactly("user-1", "assistant-runtime");
        Conversation.Message assistant = conversation.getMessages().get(1);
        assertThat(assistant.getContent())
            .isEqualTo("完整的客户交易分析报告。")
            .doesNotContain("[evidence:", "tool://");
        assertThat(String.valueOf(assistant.getUiResponse().get("answer")))
            .isEqualTo("完整的客户交易分析报告。")
            .doesNotContain("[evidence:", "tool://");
    }

    private ChatMessageIndexEntity index(String id, String role, String rocksKey, Instant createdAt) {
        ChatMessageIndexEntity index = new ChatMessageIndexEntity();
        index.setMessageId(id);
        index.setSessionId("conversation-1");
        index.setTenantId("tenant-1");
        index.setUserId("user-1");
        index.setRole(role);
        index.setRocksKey(rocksKey);
        index.setCreatedAt(createdAt);
        return index;
    }

    private ChatMessageDetail detail(String id, String role, String content, String taskId) {
        return ChatMessageDetail.builder()
            .messageId(id)
            .sessionId("conversation-1")
            .tenantId("tenant-1")
            .userId("user-1")
            .role(role)
            .content(content)
            .uiResponse("assistant".equals(role) ? Map.of("answer", content) : Map.of())
            .createdAt(Instant.parse("2026-07-31T01:00:00Z"))
            .taskId(taskId)
            .build();
    }

    private Conversation.Message message(String id, String role, String content) {
        return Conversation.Message.builder().id(id).role(role).content(content).build();
    }
}
