create table knowledge_ir_unit (
    id bigint generated by default as identity primary key,
    knowledge_id varchar(160) not null,
    document_id varchar(160) not null,
    tenant_id varchar(100) not null,
    owner_user_id varchar(100),
    visibility varchar(20),
    permission_roles clob,
    tags_json clob,
    version varchar(80),
    domain varchar(200),
    knowledge_type varchar(40) not null,
    title varchar(500),
    semantic_description clob,
    rules_json clob,
    constraints_json clob,
    applicable_intents_json clob,
    required_inputs_json clob,
    compact_representation clob not null,
    search_text clob not null,
    source_id varchar(200),
    source_chunk_id varchar(200),
    source_document_name varchar(500),
    source_section varchar(500),
    source_citation clob,
    relevance double precision,
    active boolean default true,
    created_at bigint,
    updated_at bigint,
    constraint uk_knowledge_ir_doc_unit unique (document_id, knowledge_id)
);

create index idx_knowledge_ir_document on knowledge_ir_unit (document_id, active);
create index idx_knowledge_ir_tenant_type on knowledge_ir_unit (tenant_id, knowledge_type, active);

