package com.chatchat.runtime.news.model;

public enum NewsSourceType {
    RSS,
    API,
    EXCHANGE_HOME,
    NEWS_HOME,
    SZSE_HOME,
    HKEX_HOME,
    CSINDEX_HOME,
    EXCHANGE_MARKET_DATA,
    SZSE_DISCLOSURE,
    STCN_DISCLOSURES,
    CNINFO_HOME,
    CLS_TELEGRAPH,
    EASTMONEY_724,
    STRUCTURED_FLASH,
    CNINFO_ANNOUNCEMENTS,
    SSE_ANNOUNCEMENTS,
    WEB_LIST,
    WEB_SINGLE_PAGE
}
