// @vitest-environment jsdom

import { afterEach, describe, expect, it } from "vitest";
import {
  isRawDataBlock,
  matchesConfiguredVisualizationKeyword,
  selectConfiguredVisualizationDimensions,
  visualizationRowCount
} from "./VisualizationRenderer.js";
import { configureTrendSemantics } from "../utils/trendSemantics.js";

describe("automatic visualization semantics", () => {
  afterEach(() => configureTrendSemantics());

  it("uses the configured keyword table to admit automatic charts", () => {
    configureTrendSemantics({ keywords: ["收益率", "回撤"] });

    expect(matchesConfiguredVisualizationKeyword({
      title: "客户收益率趋势",
      dataset: {
        xKey: "日期",
        columns: ["日期", "收益率"],
        series: [{ name: "收益率", yKey: "收益率" }]
      }
    })).toBe(true);
    expect(matchesConfiguredVisualizationKeyword({
      title: "数据库连接列表",
      dataset: {
        xKey: "连接名",
        columns: ["连接名", "数量"],
        series: [{ name: "数量", yKey: "数量" }]
      }
    })).toBe(false);
  });

  it("uses matching configured fields as the automatic chart dimensions", () => {
    configureTrendSemantics({ keywords: ["收益率", "客户类型"] });
    const selected = selectConfiguredVisualizationDimensions({
      type: "chart",
      chartType: "bar",
      automation: { autoGenerated: true, selectionMode: "configured_keyword" },
      dataset: {
        columns: ["客户类型", "资产", "收益率", "客户数"],
        xKey: "客户类型",
        series: [
          { name: "资产", yKey: "资产" },
          { name: "客户数", yKey: "客户数" }
        ],
        rows: [
          { 客户类型: "活跃", 资产: 100, 收益率: 4.2, 客户数: 8 },
          { 客户类型: "稳健", 资产: 80, 收益率: 1.6, 客户数: 5 }
        ]
      }
    });

    expect(selected.dataset.xKey).toBe("客户类型");
    expect(selected.dataset.series).toEqual([{ name: "收益率", yKey: "收益率" }]);
    expect(selected.automation.selectedDimensions).toEqual(["客户类型", "收益率"]);
  });

  it("does not let a title keyword select an unrelated automatic chart", () => {
    configureTrendSemantics({ keywords: ["收益率"] });
    expect(selectConfiguredVisualizationDimensions({
      type: "chart",
      title: "收益率分析",
      automation: { autoGenerated: true, selectionMode: "configured_keyword" },
      dataset: {
        columns: ["连接名", "数量"],
        xKey: "连接名",
        series: [{ name: "数量", yKey: "数量" }],
        rows: [{ 连接名: "A", 数量: 2 }, { 连接名: "B", 数量: 3 }]
      }
    })).toBeNull();
  });

  it("identifies table blocks as collapsible raw data", () => {
    expect(isRawDataBlock({ type: "table", spec: { type: "table" } })).toBe(true);
    expect(isRawDataBlock({ type: "chart", spec: { type: "chart" } })).toBe(false);
    expect(visualizationRowCount({ dataset: { rowCount: 360, rows: [{ id: 1 }] } })).toBe(360);
  });
});
