package com.chatchat.agents.orchestration.answer;

import com.chatchat.common.interaction.InteractionToolTrace;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class AgentResultPresentationServiceTest {

    @Test
    @SuppressWarnings("unchecked")
    void marksAutomaticChartsForKeywordSelectionAndRawRowsCollapsed() throws Exception {
        Map<String, Object> output = Map.of(
            "columns", List.of("日期", "收益率"),
            "rows", List.of(
                Map.of("日期", "2026-09-01", "收益率", 1.2),
                Map.of("日期", "2026-09-02", "收益率", -0.4)));
        InteractionToolTrace trace = InteractionToolTrace.builder()
            .toolName("sql_query_execute")
            .displayName("收益率趋势")
            .success(true)
            .output(new ObjectMapper().writeValueAsString(output))
            .build();

        Map<String, Object> panel = new AgentResultPresentationService(new ObjectMapper())
            .toolResultVisualizationSpec(List.of(trace));

        assertThat(panel).containsEntry("type", "panel");
        assertThat((Map<String, Object>) panel.get("ui"))
            .containsEntry("rawDataDefaultCollapsed", true);
        List<Map<String, Object>> blocks = (List<Map<String, Object>>) panel.get("blocks");
        Map<String, Object> chart = (Map<String, Object>) blocks.get(0).get("spec");
        assertThat((Map<String, Object>) chart.get("automation"))
            .containsEntry("autoGenerated", true)
            .containsEntry("selectionMode", "configured_keyword");
        assertThat((List<String>) ((Map<String, Object>) chart.get("dataset")).get("columns"))
            .hasSize(2);
        Map<String, Object> table = (Map<String, Object>) blocks.get(1).get("spec");
        assertThat((Map<String, Object>) table.get("ui"))
            .containsEntry("role", "raw_data")
            .containsEntry("defaultCollapsed", true);
    }

    @Test
    void batchEvidenceAllowsResultWithoutTemplateIdentity() throws Exception {
        Map<String, Object> output = Map.of(
            "batchId", "batch-1",
            "status", "SUCCESS",
            "results", List.of(Map.of(
                "callId", "call-1",
                "status", "SUCCESS",
                "evidenceUsable", true,
                "output", Map.of("data", Map.of(
                    "columns", List.of("Variable_name", "Value"),
                    "rows", List.of(Map.of(
                        "Variable_name", "Innodb_buffer_pool_pages_free",
                        "Value", "8192")))))));
        InteractionToolTrace trace = InteractionToolTrace.builder()
            .toolName("sql_query_execute")
            .displayName("InnoDB diagnostics")
            .success(true)
            .output(new ObjectMapper().writeValueAsString(output))
            .build();

        List<Map<String, Object>> evidence =
            new AgentResultPresentationService(new ObjectMapper())
                .toolResultEvidence(List.of(trace));

        assertThat(evidence).hasSize(1);
        assertThat(evidence.get(0))
            .containsEntry("evidenceType", "result_set_batch")
            .containsEntry("resultSetCount", 1)
            .containsEntry("usableResultSetCount", 1);
        assertThat(evidence.get(0)).doesNotContainKey("templateIds");
    }
}
