spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:./data/chatchat-news;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE"
    username: sa
    password: news_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
