-- Securities document-library business categories. They are persisted independently of
-- document tags so empty categories remain available before the first document is uploaded.
insert into kb_document_business_category (builtin, sort_order, created_at, updated_at, id, code, name, description) values
    (true, 10, current_timestamp, current_timestamp, 'kbcat-market-data', 'market_data', '市场行情', '交易所行情、指数、成交、估值及市场统计资料'),
    (true, 20, current_timestamp, current_timestamp, 'kbcat-macro-policy', 'macro_policy', '宏观政策', '宏观经济、货币财政政策及监管政策资料'),
    (true, 30, current_timestamp, current_timestamp, 'kbcat-industry-research', 'industry_research', '行业研究', '行业周期、产业链、竞争格局及景气跟踪资料'),
    (true, 40, current_timestamp, current_timestamp, 'kbcat-company-research', 'company_research', '公司研究', '上市公司基本面、治理、调研及估值资料'),
    (true, 50, current_timestamp, current_timestamp, 'kbcat-periodic-report', 'periodic_report', '定期报告', '上市公司年报、半年报、季报及摘要'),
    (true, 60, current_timestamp, current_timestamp, 'kbcat-announcement', 'announcement', '临时公告', '上市公司临时公告、重大事项及监管问询回复'),
    (true, 70, current_timestamp, current_timestamp, 'kbcat-research-report', 'research_report', '研究报告', '内部与外部研究报告、路演纪要及专家观点'),
    (true, 80, current_timestamp, current_timestamp, 'kbcat-investment-strategy', 'investment_strategy', '投资策略', '大势研判、资产配置、组合策略及投资建议资料'),
    (true, 90, current_timestamp, current_timestamp, 'kbcat-fixed-income', 'fixed_income', '固定收益', '利率债、信用债、可转债及资产证券化资料'),
    (true, 100, current_timestamp, current_timestamp, 'kbcat-fund-product', 'fund_product', '基金产品', '公募基金、私募基金、资管计划及产品评价资料'),
    (true, 110, current_timestamp, current_timestamp, 'kbcat-derivatives', 'derivatives', '衍生品', '期货、期权、互换、结构化产品及套期保值资料'),
    (true, 120, current_timestamp, current_timestamp, 'kbcat-investment-banking', 'investment_banking', '投行业务', '股权融资、债券融资、并购重组及尽职调查资料'),
    (true, 130, current_timestamp, current_timestamp, 'kbcat-wealth-management', 'wealth_management', '财富管理', '客户分层、资产配置、产品适配及投后服务资料'),
    (true, 140, current_timestamp, current_timestamp, 'kbcat-brokerage', 'brokerage', '经纪业务', '客户运营、渠道、分支机构及交易服务资料'),
    (true, 150, current_timestamp, current_timestamp, 'kbcat-institutional', 'institutional', '机构业务', '机构客户、研究销售、主经纪商及综合金融服务资料'),
    (true, 160, current_timestamp, current_timestamp, 'kbcat-compliance-policy', 'compliance_policy', '合规制度', '法律法规、自律规则、公司制度及合规审查资料'),
    (true, 170, current_timestamp, current_timestamp, 'kbcat-risk-management', 'risk_management', '风险管理', '市场、信用、流动性、操作及模型风险资料'),
    (true, 180, current_timestamp, current_timestamp, 'kbcat-operations', 'operations', '运营管理', '清算交收、账户、资金、估值核算及运营流程资料'),
    (true, 190, current_timestamp, current_timestamp, 'kbcat-data-standard', 'data_standard', '数据标准', '数据字典、指标口径、数据质量及接口规范'),
    (true, 200, current_timestamp, current_timestamp, 'kbcat-training', 'training', '培训资料', '证券业务培训、操作手册、案例与知识学习资料');

-- Financial-securities starter data. Exactly five skills and five Agents are published;
-- the remaining records are editable drafts and therefore do not bypass publication quotas.
insert into ds_domain_skill_category (created_at, updated_at, id, tenant_id, name) values
    (current_timestamp, current_timestamp, 'dscat-securities-market', 'default', '证券市场'),
    (current_timestamp, current_timestamp, 'dscat-macro-strategy', 'default', '宏观策略'),
    (current_timestamp, current_timestamp, 'dscat-industry-research', 'default', '行业研究'),
    (current_timestamp, current_timestamp, 'dscat-company-research', 'default', '公司研究'),
    (current_timestamp, current_timestamp, 'dscat-financial-analysis', 'default', '财务分析'),
    (current_timestamp, current_timestamp, 'dscat-valuation-pricing', 'default', '估值定价'),
    (current_timestamp, current_timestamp, 'dscat-asset-allocation', 'default', '资产配置'),
    (current_timestamp, current_timestamp, 'dscat-portfolio-management', 'default', '投资组合'),
    (current_timestamp, current_timestamp, 'dscat-market-risk', 'default', '市场风险'),
    (current_timestamp, current_timestamp, 'dscat-compliance', 'default', '合规风控'),
    (current_timestamp, current_timestamp, 'dscat-investment-banking', 'default', '投行业务'),
    (current_timestamp, current_timestamp, 'dscat-wealth-management', 'default', '财富管理'),
    (current_timestamp, current_timestamp, 'dscat-brokerage', 'default', '经纪业务'),
    (current_timestamp, current_timestamp, 'dscat-institutional', 'default', '机构业务'),
    (current_timestamp, current_timestamp, 'dscat-fixed-income', 'default', '固定收益'),
    (current_timestamp, current_timestamp, 'dscat-derivatives', 'default', '衍生品'),
    (current_timestamp, current_timestamp, 'dscat-quant-research', 'default', '量化研究'),
    (current_timestamp, current_timestamp, 'dscat-disclosure', 'default', '信息披露'),
    (current_timestamp, current_timestamp, 'dscat-credit-research', 'default', '信用研究'),
    (current_timestamp, current_timestamp, 'dscat-securities-operations', 'default', '运营管理');

insert into ds_domain_skill (builtin, publication_dirty, created_at, published_at, updated_at, source_type, status, id, owner_id, tenant_id, category, name, description, search_text, markdown_content) values
    (true, false, current_timestamp, current_timestamp, current_timestamp, 'SQL', 'PUBLISHED', 'builtin-securities-market', 'system', 'default', '证券市场', '证券市场行情分析', '分析沪深交易所行情、指数、成交结构、资金与市场微观结构。', '证券市场 证券行情 指数 成交 资金 市场微观结构', '# 证券市场行情分析  ## 目标 基于可追溯行情数据解释市场变化，区分事实、推断与风险。'),
    (true, false, current_timestamp, current_timestamp, current_timestamp, 'SQL', 'PUBLISHED', 'builtin-macro-strategy', 'system', 'default', '宏观策略', '宏观策略分析', '分析宏观经济、政策、利率、汇率及其对资本市场的传导。', '宏观策略 经济 政策 利率 汇率 资本市场', '# 宏观策略分析  ## 目标 建立宏观变量到资产价格的传导链并给出情景分析。'),
    (true, false, current_timestamp, current_timestamp, current_timestamp, 'SQL', 'PUBLISHED', 'builtin-industry-research', 'system', 'default', '行业研究', '证券行业研究', '研究行业周期、产业链、竞争格局、政策与关键经营指标。', '行业研究 产业链 竞争格局 周期 政策', '# 证券行业研究  ## 目标 从产业链、供需、竞争和估值维度形成行业判断。'),
    (true, false, current_timestamp, current_timestamp, current_timestamp, 'SQL', 'PUBLISHED', 'builtin-company-research', 'system', 'default', '公司研究', '上市公司基本面研究', '分析上市公司商业模式、经营质量、竞争优势、治理与风险。', '上市公司 基本面 商业模式 公司治理 竞争优势', '# 上市公司基本面研究  ## 目标 基于公告和财务数据形成可验证的公司研究结论。'),
    (true, false, current_timestamp, current_timestamp, current_timestamp, 'SQL', 'PUBLISHED', 'builtin-financial-analysis', 'system', 'default', '财务分析', '上市公司财务分析', '分析利润表、资产负债表、现金流量表及财务质量。', '财务分析 三大报表 盈利 现金流 财务质量', '# 上市公司财务分析  ## 目标 识别盈利质量、现金流、偿债能力和异常会计信号。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-valuation-pricing', 'system', 'default', '估值定价', '证券估值与定价', '使用相对估值、现金流折现和情景分析评估证券价值。', '证券估值 相对估值 DCF 情景分析', '# 证券估值与定价  ## 目标 明确假设、口径和敏感性，不将估值结论表述为收益承诺。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-asset-allocation', 'system', 'default', '资产配置', '大类资产配置', '结合目标、期限、风险预算与市场情景设计资产配置方案。', '资产配置 风险预算 市场情景 再平衡', '# 大类资产配置  ## 目标 在约束条件下配置风险并设计再平衡规则。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-portfolio-management', 'system', 'default', '投资组合', '投资组合诊断', '分析组合暴露、归因、集中度、回撤与再平衡需求。', '投资组合 绩效归因 集中度 回撤 再平衡', '# 投资组合诊断  ## 目标 从收益、风险、暴露和约束四个维度诊断组合。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-market-risk', 'system', 'default', '市场风险', '市场风险分析', '评估波动率、相关性、风险价值、压力测试与流动性风险。', '市场风险 VaR 压力测试 波动率 流动性', '# 市场风险分析  ## 目标 量化风险暴露并说明模型边界和压力情景。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-compliance', 'system', 'default', '合规风控', '证券合规审查', '识别适当性、信息隔离、异常交易、宣传材料和利益冲突风险。', '证券合规 适当性 异常交易 信息隔离 利益冲突', '# 证券合规审查  ## 目标 依据适用制度形成问题、依据、风险和整改建议。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-investment-banking', 'system', 'default', '投行业务', '投资银行项目分析', '支持股权融资、债券融资、并购重组项目的材料与风险分析。', '投资银行 IPO 再融资 债券 并购重组', '# 投资银行项目分析  ## 目标 梳理项目条件、尽调证据、审核关注和执行风险。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-wealth-management', 'system', 'default', '财富管理', '财富管理需求分析', '分析客户目标、风险承受能力、产品适配与持续服务方案。', '财富管理 客户画像 风险测评 产品适配', '# 财富管理需求分析  ## 目标 坚持适当性原则并明确产品风险与客户约束。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-brokerage', 'system', 'default', '经纪业务', '证券经纪业务分析', '分析客户交易、渠道运营、服务转化、留存及分支机构经营。', '证券经纪 客户运营 渠道 分支机构 留存', '# 证券经纪业务分析  ## 目标 用合规口径诊断客户经营与渠道效率。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-institutional', 'system', 'default', '机构业务', '机构客户服务分析', '分析机构客户需求、研究服务、交易服务和综合金融协同。', '机构业务 机构客户 研究服务 交易服务', '# 机构客户服务分析  ## 目标 围绕机构客户旅程识别服务缺口和协同机会。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-fixed-income', 'system', 'default', '固定收益', '固定收益证券分析', '分析利率债、信用债、收益率曲线、久期、利差与流动性。', '固定收益 债券 收益率曲线 久期 信用利差', '# 固定收益证券分析  ## 目标 分解利率、信用、流动性和期限结构风险。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-derivatives', 'system', 'default', '衍生品', '衍生品策略与风险', '分析期货期权结构、希腊字母、套期保值和保证金风险。', '衍生品 期货 期权 希腊字母 套期保值', '# 衍生品策略与风险  ## 目标 解释收益结构、极端损失、保证金和对手方风险。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-quant-research', 'system', 'default', '量化研究', '量化策略研究', '支持因子研究、回测设计、归因、稳健性检验与模型风险管理。', '量化研究 因子 回测 归因 模型风险', '# 量化策略研究  ## 目标 防止未来函数、过拟合和样本偏差，保证结果可复现。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-disclosure', 'system', 'default', '信息披露', '上市公司信息披露分析', '解析公告、定期报告、监管问询与重大事项的影响。', '信息披露 公告 定期报告 监管问询 重大事项', '# 上市公司信息披露分析  ## 目标 提取事件、时间、主体、口径和潜在市场影响。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-credit-research', 'system', 'default', '信用研究', '发行人信用研究', '分析发行人偿债能力、现金流、担保、条款和信用事件。', '信用研究 发行人 偿债能力 债券条款 信用事件', '# 发行人信用研究  ## 目标 识别信用基本面、外部支持、条款保护和尾部风险。'),
    (true, false, current_timestamp, null, current_timestamp, 'SQL', 'DRAFT', 'builtin-securities-operations', 'system', 'default', '运营管理', '证券业务运营分析', '分析清算交收、账户、资金、估值核算、运营质量和操作风险。', '证券运营 清算交收 账户 估值核算 操作风险', '# 证券业务运营分析  ## 目标 识别流程断点、数据差异、操作风险和控制措施。');

insert into skill_config (builtin, default_agent, created_at, updated_at, default_mode, market_status, id, label, description, usage_scenarios_json, skill_tags_json, system_prompt, first_use_greeting, workflow_config_json, quick_questions_json) values
    (true, true, current_timestamp, current_timestamp, 'agent_chat', 'published', 'securities_market_agent', '证券市场行情分析 Agent', '分析交易所行情、指数、成交结构与市场微观结构。', '["行情复盘","指数分析","成交结构"]', '["证券市场","行情分析"]', '你是证券市场行情分析 Agent。仅基于可追溯数据解释行情变化，明确区分事实、推断与风险，不提供收益承诺。', '请提供市场范围、日期和希望分析的指标。', '{"boundDomainSkillIds":["builtin-securities-market"]}', '["复盘今日沪深市场行情","分析主要指数和成交结构"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'published', 'macro_strategy_agent', '宏观策略分析 Agent', '分析宏观经济与政策变量对资本市场的传导。', '["宏观研判","政策解读","资产影响"]', '["宏观策略","政策研究"]', '你是证券公司的宏观策略分析 Agent。建立宏观变量、政策变化与资产价格之间的证据链，提供多情景分析。', '请说明关注的宏观事件、市场和分析期限。', '{"boundDomainSkillIds":["builtin-macro-strategy"]}', '["分析最新政策对A股的影响","构建利率变化情景"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'published', 'industry_research_agent', '证券行业研究 Agent', '研究行业周期、产业链、竞争格局与估值。', '["行业比较","产业链研究","景气跟踪"]', '["行业研究","产业链"]', '你是证券行业研究 Agent。基于产业数据、公司公告和政策信息分析供需、竞争、盈利与估值，不编造数据。', '请提供行业、研究区间和关注问题。', '{"boundDomainSkillIds":["builtin-industry-research"]}', '["分析行业景气度变化","比较行业内主要公司"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'published', 'company_research_agent', '上市公司研究 Agent', '研究上市公司基本面、治理、竞争优势与风险。', '["公司研究","公告解读","基本面跟踪"]', '["上市公司","基本面"]', '你是上市公司研究 Agent。以公告、财务报告和可靠市场数据为依据，输出商业模式、经营质量、治理和风险分析。', '请提供公司名称、证券代码和研究目标。', '{"boundDomainSkillIds":["builtin-company-research"]}', '["生成上市公司研究提纲","分析公司最新公告"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'published', 'financial_analysis_agent', '上市公司财务分析 Agent', '分析三大报表、财务质量和异常信号。', '["财报分析","财务诊断","同业比较"]', '["财务分析","财务报表"]', '你是上市公司财务分析 Agent。统一会计口径，分析盈利质量、现金流、资产负债和异常变化，说明数据期间与来源。', '请提供财务报表、公司和比较期间。', '{"boundDomainSkillIds":["builtin-financial-analysis"]}', '["分析公司本期财务质量","比较两家公司财务指标"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'valuation_pricing_agent', '证券估值定价 Agent', '使用多种方法进行证券估值和敏感性分析。', '["股票估值","估值比较","敏感性分析"]', '["估值定价"]', '你是证券估值定价 Agent。明确假设、口径和敏感性，输出估值区间及风险，不作收益保证。', '请提供标的、预测数据和估值日期。', '{"boundDomainSkillIds":["builtin-valuation-pricing"]}', '["建立公司估值框架","分析估值敏感性"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'asset_allocation_agent', '大类资产配置 Agent', '根据目标、风险预算和市场情景设计资产配置。', '["战略配置","战术配置","再平衡"]', '["资产配置"]', '你是证券公司的资产配置 Agent。根据目标、期限、流动性和风险预算构建方案，并披露情景风险。', '请提供投资目标、期限和风险约束。', '{"boundDomainSkillIds":["builtin-asset-allocation"]}', '["设计大类资产配置方案","制定组合再平衡规则"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'portfolio_management_agent', '投资组合诊断 Agent', '分析组合暴露、归因、集中度与回撤。', '["组合诊断","绩效归因","风险暴露"]', '["投资组合"]', '你是投资组合诊断 Agent。基于持仓和基准数据分析收益归因、风险暴露、集中度和再平衡需求。', '请提供组合持仓、基准和评估区间。', '{"boundDomainSkillIds":["builtin-portfolio-management"]}', '["诊断投资组合风险","完成组合绩效归因"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'market_risk_agent', '市场风险分析 Agent', '评估市场风险、压力情景和流动性风险。', '["风险计量","压力测试","限额监控"]', '["市场风险","风险管理"]', '你是证券公司市场风险分析 Agent。量化风险暴露，说明模型假设、数据边界、压力情景和控制建议。', '请提供头寸、风险因子和计量口径。', '{"boundDomainSkillIds":["builtin-market-risk"]}', '["设计市场风险压力测试","分析组合风险暴露"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'compliance_agent', '证券合规审查 Agent', '识别证券业务适当性、异常交易与利益冲突风险。', '["合规审查","制度检查","整改建议"]', '["合规风控"]', '你是证券合规审查 Agent。依据适用规则形成问题、依据、风险等级和整改建议，重大事项必须提示人工复核。', '请提供业务场景、材料和适用制度。', '{"boundDomainSkillIds":["builtin-compliance"]}', '["审查业务方案合规风险","生成合规检查清单"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'investment_banking_agent', '投资银行项目 Agent', '支持股权、债券和并购项目分析。', '["IPO尽调","债券项目","并购重组"]', '["投资银行"]', '你是投资银行项目 Agent。围绕项目条件、尽调证据、审核关注和执行风险进行分析，不替代保荐和法律判断。', '请提供项目类型、阶段和已有材料。', '{"boundDomainSkillIds":["builtin-investment-banking"]}', '["生成IPO尽调清单","分析债券项目风险"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'wealth_management_agent', '财富管理分析 Agent', '分析客户需求、风险承受能力和产品适配。', '["客户画像","产品适配","投后服务"]', '["财富管理","适当性"]', '你是证券财富管理分析 Agent。坚持投资者适当性原则，明确客户约束、产品风险和持续服务要求。', '请提供客户目标、期限、流动性和风险等级。', '{"boundDomainSkillIds":["builtin-wealth-management"]}', '["分析客户资产配置需求","检查产品适配性"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'brokerage_agent', '证券经纪业务 Agent', '分析经纪客户、渠道、服务与分支机构经营。', '["客户经营","渠道分析","分支机构诊断"]', '["经纪业务"]', '你是证券经纪业务分析 Agent。使用合规口径分析客户分层、交易行为、渠道效率、留存和服务机会。', '请提供经营范围、客户指标和分析期间。', '{"boundDomainSkillIds":["builtin-brokerage"]}', '["分析经纪客户流失","诊断分支机构经营"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'institutional_agent', '机构业务分析 Agent', '分析机构客户需求和综合金融服务。', '["机构客户","研究服务","交易服务"]', '["机构业务"]', '你是证券机构业务分析 Agent。围绕客户旅程分析研究、交易、托管及综合金融协同机会与风险。', '请提供机构类型、业务数据和目标。', '{"boundDomainSkillIds":["builtin-institutional"]}', '["分析机构客户服务需求","设计机构业务协同方案"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'fixed_income_agent', '固定收益研究 Agent', '分析利率债、信用债和收益率曲线。', '["利率研究","信用利差","债券组合"]', '["固定收益","债券"]', '你是固定收益研究 Agent。分解利率、信用、期限、流动性和条款风险，明确行情与估值口径。', '请提供债券、曲线日期和研究目标。', '{"boundDomainSkillIds":["builtin-fixed-income"]}', '["分析收益率曲线变化","评估债券利差风险"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'derivatives_agent', '衍生品策略风险 Agent', '分析期货期权策略、套保和保证金风险。', '["期权策略","期货套保","风险测算"]', '["衍生品"]', '你是衍生品策略风险 Agent。解释收益结构、希腊字母、极端损失、保证金和对手方风险。', '请提供合约、头寸、策略目标和风险约束。', '{"boundDomainSkillIds":["builtin-derivatives"]}', '["分析期权组合风险","设计期货套保方案"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'quant_research_agent', '量化策略研究 Agent', '支持因子、回测、归因和稳健性检验。', '["因子研究","策略回测","模型验证"]', '["量化研究"]', '你是量化策略研究 Agent。严格控制未来函数、过拟合、幸存者偏差和交易成本，保证研究可复现。', '请提供数据范围、策略假设和回测约束。', '{"boundDomainSkillIds":["builtin-quant-research"]}', '["设计因子回测方案","检查量化策略偏差"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'disclosure_agent', '信息披露分析 Agent', '解析公告、定期报告和监管问询。', '["公告解析","监管问询","事件影响"]', '["信息披露"]', '你是上市公司信息披露分析 Agent。准确提取事件、时间、主体、数据口径和不确定性，引用原始披露材料。', '请提供公告、证券代码和关注事项。', '{"boundDomainSkillIds":["builtin-disclosure"]}', '["解析上市公司公告","总结监管问询关注点"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'credit_research_agent', '发行人信用研究 Agent', '分析发行人偿债能力、条款和信用事件。', '["信用分析","发行人研究","债券条款"]', '["信用研究"]', '你是发行人信用研究 Agent。分析现金流、杠杆、偿债安排、外部支持、担保和债券条款，突出尾部风险。', '请提供发行人、债券和分析期间。', '{"boundDomainSkillIds":["builtin-credit-research"]}', '["评估发行人信用风险","分析债券保护条款"]'),
    (true, false, current_timestamp, current_timestamp, 'agent_chat', 'draft', 'securities_operations_agent', '证券业务运营 Agent', '分析清算、账户、资金、估值核算与操作风险。', '["清算交收","运营质量","操作风险"]', '["运营管理"]', '你是证券业务运营分析 Agent。识别流程断点、数据差异、控制缺陷和操作风险，给出可验证的整改措施。', '请提供业务流程、异常记录和系统范围。', '{"boundDomainSkillIds":["builtin-securities-operations"]}', '["分析清算交收异常","设计运营风险检查清单"]');
