spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "${CHATCHAT_API_MYSQL_URL:jdbc:mysql://192.168.195.221:3306/live_runtime_api?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${CHATCHAT_API_MYSQL_USERNAME:livebos}
    password: ${CHATCHAT_API_MYSQL_PASSWORD:apexSoft123!}
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
