-- Standalone chatchat-runtime-news schema (H2)
create table if not exists news_source (
  id bigint generated by default as identity primary key, capability_id bigint default 1 not null,
  source_code varchar(64) not null, source_name varchar(128) not null, source_type varchar(32) not null,
  entry_url varchar(2000) not null, allowed_domain varchar(255), schedule_cron varchar(128), enabled boolean not null,
  configuration_json varchar(8000), last_cursor varchar(2000), last_collected_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null,
  constraint uk_news_source_code unique (source_code)
);
create table if not exists news_source_rule (
  id bigint generated by default as identity primary key, source_id bigint not null,
  list_selector varchar(1000), link_selector varchar(1000), title_selector varchar(1000),
  content_selector varchar(1000), author_selector varchar(1000), publish_time_selector varchar(1000),
  url_pattern varchar(1000), updated_at timestamp(6) with time zone not null,
  constraint uk_news_source_rule unique (source_id)
);
create table if not exists news_collect_record (
  id bigint generated by default as identity primary key, source_id bigint not null, source_url varchar(2000) not null,
  url_hash varchar(64) not null, content_hash varchar(64), publish_time timestamp(6) with time zone,
  collect_status varchar(32) not null, analysis_status varchar(32) not null, document_id varchar(128),
  collected_at timestamp(6) with time zone, error_message varchar(4000),
  constraint uk_news_url_hash unique (url_hash)
);
create table if not exists news_analysis_task (
  id bigint generated by default as identity primary key, document_id varchar(128) not null, source_id bigint not null,
  status varchar(32) not null, created_at timestamp(6) with time zone not null,
  updated_at timestamp(6) with time zone not null, error_message varchar(4000),
  constraint uk_news_analysis_document unique (document_id)
);
