-- Standalone chatchat-runtime-news schema (H2)
create table if not exists news_source (
  id bigint generated by default as identity primary key, capability_id bigint default 1 not null,
  source_code varchar(64) not null, source_name varchar(128) not null, source_type varchar(32) not null,
  entry_url varchar(2000) not null, allowed_domain varchar(255), schedule_cron varchar(128), enabled boolean not null,
  configuration_json varchar(8000), last_cursor varchar(2000), last_collected_at timestamp(6) with time zone,
  created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null,
  constraint uk_news_source_code unique (source_code)
);
create table if not exists news_source_rule (
  id bigint generated by default as identity primary key, source_id bigint not null,
  list_selector varchar(1000), link_selector varchar(1000), title_selector varchar(1000),
  content_selector varchar(1000), author_selector varchar(1000), publish_time_selector varchar(1000),
  url_pattern varchar(1000), updated_at timestamp(6) with time zone not null,
  constraint uk_news_source_rule unique (source_id)
);
create table if not exists news_collect_record (
  id bigint generated by default as identity primary key, source_id bigint not null, source_url varchar(2000) not null,
  url_hash varchar(64) not null, content_hash varchar(64), publish_time timestamp(6) with time zone,
  collect_status varchar(32) not null, analysis_status varchar(32) not null, document_id varchar(128),
  collected_at timestamp(6) with time zone, error_message varchar(4000),
  constraint uk_news_url_hash unique (url_hash)
);
create index if not exists idx_news_collect_record_collected_at on news_collect_record (collected_at);
create table if not exists news_analysis_task (
  id bigint generated by default as identity primary key, document_id varchar(128) not null, source_id bigint not null,
  status varchar(32) not null, created_at timestamp(6) with time zone not null,
  updated_at timestamp(6) with time zone not null, error_message varchar(4000),
  constraint uk_news_analysis_document unique (document_id)
);

-- Governed financial-market storage. Dataset-specific business columns are added by
-- FinancialDataStore when the first observation arrives. Weekly archive tables are
-- deliberately created lazily after those dynamic columns are known.
create table if not exists market_asset_catalog (
  id bigint generated by default as identity primary key,
  dataset_code varchar(64) not null, asset_name varchar(160) not null,
  business_description varchar(4000) not null, business_tags_json varchar(4000) not null,
  database_name varchar(128) not null, table_name varchar(128) not null,
  update_frequency varchar(128), source_names_json varchar(4000),
  last_observation_date date, last_collected_at timestamp,
  archive_table_name varchar(128), hot_retention_days integer, archive_retention_days integer,
  history_granularity varchar(64), created_at timestamp not null, updated_at timestamp not null,
  constraint uk_market_asset_code unique (dataset_code)
);

create table if not exists data_schema_registry (
  id bigint generated by default as identity primary key,
  dataset_code varchar(64) not null, table_name varchar(128) not null,
  field_name varchar(128) not null, source_field varchar(128) not null,
  field_type varchar(32) not null, business_description varchar(1000),
  schema_version integer not null, created_at timestamp not null, updated_at timestamp not null,
  constraint uk_data_schema_field unique (dataset_code, field_name)
);
create index if not exists idx_data_schema_dataset on data_schema_registry (dataset_code);

create table if not exists security_master (
  id bigint generated by default as identity primary key,
  exchange_code varchar(8) not null, security_code varchar(16) not null,
  security_name varchar(160) not null, security_full_name varchar(300),
  security_type varchar(32) not null, board_name varchar(64), listing_date date,
  industry_name varchar(160), source_url varchar(1000) not null,
  source_refreshed_at timestamp not null, created_at timestamp not null, updated_at timestamp not null,
  constraint uk_security_master_code unique (exchange_code, security_code)
);
create index if not exists idx_security_master_code on security_master (security_code);
create index if not exists idx_security_master_name on security_master (security_name);

create table if not exists market_quote_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_market_quote_daily_record unique (record_key)
);
create index if not exists idx_market_quote_daily_collected_date on market_quote_daily (collected_date, observation_date);
create index if not exists idx_market_quote_daily_observation_date on market_quote_daily (observation_date);

create table if not exists stock_valuation_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_stock_valuation_daily_record unique (record_key)
);
create index if not exists idx_stock_valuation_daily_collected_date on stock_valuation_daily (collected_date, observation_date);
create index if not exists idx_stock_valuation_daily_observation_date on stock_valuation_daily (observation_date);

create table if not exists index_valuation_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_index_valuation_daily_record unique (record_key)
);
create index if not exists idx_index_valuation_daily_collected_date on index_valuation_daily (collected_date, observation_date);
create index if not exists idx_index_valuation_daily_observation_date on index_valuation_daily (observation_date);

create table if not exists margin_trade_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_margin_trade_daily_record unique (record_key)
);
create index if not exists idx_margin_trade_daily_collected_date on margin_trade_daily (collected_date, observation_date);
create index if not exists idx_margin_trade_daily_observation_date on margin_trade_daily (observation_date);

create table if not exists stock_dividend_event (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_stock_dividend_event_record unique (record_key)
);
create index if not exists idx_stock_dividend_event_collected_date on stock_dividend_event (collected_date, observation_date);
create index if not exists idx_stock_dividend_event_observation_date on stock_dividend_event (observation_date);

create table if not exists etf_scale_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_etf_scale_daily_record unique (record_key)
);
create index if not exists idx_etf_scale_daily_collected_date on etf_scale_daily (collected_date, observation_date);
create index if not exists idx_etf_scale_daily_observation_date on etf_scale_daily (observation_date);

create table if not exists market_statistics_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_market_statistics_daily_record unique (record_key)
);
create index if not exists idx_market_statistics_daily_collected_date on market_statistics_daily (collected_date, observation_date);
create index if not exists idx_market_statistics_daily_observation_date on market_statistics_daily (observation_date);

create table if not exists bond_market_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_bond_market_daily_record unique (record_key)
);
create index if not exists idx_bond_market_daily_collected_date on bond_market_daily (collected_date, observation_date);
create index if not exists idx_bond_market_daily_observation_date on bond_market_daily (observation_date);

create table if not exists bond_market_overview_monthly (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_bond_market_overview_monthly_record unique (record_key)
);
create index if not exists idx_bond_market_overview_monthly_collected_date on bond_market_overview_monthly (collected_date, observation_date);
create index if not exists idx_bond_market_overview_monthly_observation_date on bond_market_overview_monthly (observation_date);

create table if not exists bond_yield_curve_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_bond_yield_curve_daily_record unique (record_key)
);
create index if not exists idx_bond_yield_curve_daily_collected_date on bond_yield_curve_daily (collected_date, observation_date);
create index if not exists idx_bond_yield_curve_daily_observation_date on bond_yield_curve_daily (observation_date);

create table if not exists bond_counter_quote_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_bond_counter_quote_daily_record unique (record_key)
);
create index if not exists idx_bond_counter_quote_daily_collected_date on bond_counter_quote_daily (collected_date, observation_date);
create index if not exists idx_bond_counter_quote_daily_observation_date on bond_counter_quote_daily (observation_date);

create table if not exists bond_settlement_daily (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_bond_settlement_daily_record unique (record_key)
);
create index if not exists idx_bond_settlement_daily_collected_date on bond_settlement_daily (collected_date, observation_date);
create index if not exists idx_bond_settlement_daily_observation_date on bond_settlement_daily (observation_date);

create table if not exists bond_collateral_monthly (
  id bigint generated by default as identity primary key,
  collected_date date not null, observation_date date not null, collected_at timestamp not null,
  source_id bigint not null, source_code varchar(64) not null,
  source_url varchar(2000) not null, record_key varchar(64) not null, payload_json clob not null,
  constraint uk_bond_collateral_monthly_record unique (record_key)
);
create index if not exists idx_bond_collateral_monthly_collected_date on bond_collateral_monthly (collected_date, observation_date);
create index if not exists idx_bond_collateral_monthly_observation_date on bond_collateral_monthly (observation_date);
