<template>
  <section class="ds-page">
    <header class="ds-header"><div><span>能力管理 / 数据科学</span><h1>Python 数据科学工作台</h1><p>在用户专属 Docker Asset 中开发、测试并发布可供 Agent 检索的 Python 能力。</p></div><button class="ds-primary" @click="openAssetDialog">发布 Python Asset</button></header>
    <nav class="ds-tabs"><button v-for="item in tabs" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id">{{ item.label }}</button></nav>
    <p v-if="error" class="ds-alert error">{{ error }}</p><p v-if="message" class="ds-alert success">{{ message }}</p>

    <div v-if="loading" class="ds-empty">正在加载数据科学工作台…</div>
    <template v-else-if="tab==='environment'">
      <div v-if="!assets.length" class="ds-empty"><strong>当前没有可用的数据科学环境</strong><p>请先发布 Python Asset。只有 READY 环境才允许创建、运行和发布脚本。</p><button class="ds-primary" @click="openAssetDialog">发布环境</button></div>
      <div v-else class="ds-card-grid"><article v-for="asset in assets" :key="asset.id" class="ds-card"><div class="ds-card-head"><strong>{{ asset.name }}</strong><span :class="['ds-status', statusClass(asset.status)]">{{ asset.status }}</span></div><p>{{ asset.description || '暂无环境描述' }}</p><dl><div><dt>MCP 环境</dt><dd>{{ asset.mcpEnvironmentId }} / v{{ asset.mcpEnvironmentVersion }}</dd></div><div><dt>镜像</dt><dd>{{ asset.dockerImage }}</dd></div><div><dt>资源</dt><dd>{{ asset.cpuLimit }} CPU / {{ asset.memoryLimit }} / 临时磁盘 {{ asset.diskLimit }}</dd></div><div><dt>隔离策略</dt><dd>{{ asset.runtimeUser }} / {{ asset.networkPolicy }} / {{ asset.timeoutSeconds }}s</dd></div><div><dt>Workspace</dt><dd>{{ asset.workspacePath || '-' }}</dd></div></dl><small v-if="asset.statusMessage">{{ asset.statusMessage }}</small></article></div>
    </template>

    <template v-else-if="tab==='develop'">
      <div v-if="!readyAssets.length" class="ds-empty"><strong>开发入口已锁定</strong><p>当前用户没有 READY 状态的 Python Asset，请先发布并成功创建隔离环境。</p><button class="ds-primary" @click="tab='environment'">前往 Python 环境</button></div>
      <div v-else class="ds-workspace">
        <aside class="ds-script-list"><div class="ds-list-title"><strong>脚本列表</strong><button @click="newScript">+ 新建</button></div><button v-for="script in scripts" :key="script.id" :class="{active:form.id===script.id}" @click="selectScript(script)"><strong>{{ script.fileName }}</strong><span>{{ script.status }} · v{{ script.currentVersion }}</span></button></aside>
        <main class="ds-editor"><div class="ds-editor-toolbar"><label>Asset <select v-model="form.assetId"><option v-for="asset in readyAssets" :value="asset.id" :key="asset.id">{{ asset.name }}</option></select></label><input v-model="form.fileName" placeholder="analysis.py"><button @click="save" :disabled="busy">保存</button><button @click="run" :disabled="busy||!form.id">运行</button><button class="ds-primary" @click="publishOpen=true" :disabled="busy||!canPublish">发布</button></div><textarea v-model="form.sourceCode" spellcheck="false" aria-label="Python 脚本编辑器"></textarea><div class="ds-console"><label>执行参数（JSON）<textarea v-model="parametersText" class="ds-param-input" spellcheck="false"></textarea></label><strong>执行日志</strong><pre>{{ consoleText || '保存脚本后运行，stdout / stderr 将显示在这里。' }}</pre></div></main>
      </div>
    </template>

    <template v-else><div v-if="!scripts.length" class="ds-empty">暂无脚本</div><div v-else class="ds-table-wrap"><table><thead><tr><th>脚本</th><th>Asset</th><th>版本</th><th>状态</th><th>最后测试</th><th>更新时间</th></tr></thead><tbody><tr v-for="script in scripts" :key="script.id"><td>{{ script.fileName }}</td><td>{{ assetName(script.assetId) }}</td><td>v{{ script.currentVersion }}</td><td><span :class="['ds-status',statusClass(script.status)]">{{ script.status }}</span></td><td>{{ script.lastTestSucceeded ? '成功' : '未通过' }}</td><td>{{ formatTime(script.updatedAt) }}</td></tr></tbody></table></div></template>

    <div v-if="assetOpen" class="ds-modal" @mousedown.self="assetOpen=false"><form @submit.prevent="createAsset"><h2>发布 Python Asset 环境</h2><p>只能选择 MCP 管理端已发布的环境；镜像和资源边界由 MCP 统一治理。</p><label>环境名称 *<input v-model="assetForm.name" required></label><label>环境描述<textarea v-model="assetForm.description"></textarea></label><label>MCP 已发布环境 *<select v-model="assetForm.environmentId" required><option disabled value="">请选择环境</option><option v-for="env in environmentCatalog" :key="env.id" :value="env.id">{{ env.name }} · Python {{ env.pythonVersion }} · v{{ env.versionNumber }}</option></select></label><div v-if="selectedEnvironment" class="ds-alert"><strong>{{ selectedEnvironment.dockerImage }}</strong><br>{{ selectedEnvironment.cpuLimit }} CPU / {{ selectedEnvironment.memoryLimit }} / 网络{{ selectedEnvironment.networkEnabled?'开启':'禁用' }} / 超时 {{ selectedEnvironment.timeoutSeconds }}s</div><p v-if="!environmentCatalog.length" class="ds-alert error">MCP 尚未发布 Python 环境，请先到 MCP 管理端的 Python 管理页面发布。</p><footer><button type="button" @click="assetOpen=false">取消</button><button class="ds-primary" :disabled="busy||!environmentCatalog.length">{{ busy?'创建中…':'发布环境' }}</button></footer></form></div>
    <div v-if="publishOpen" class="ds-modal" @mousedown.self="publishOpen=false"><form @submit.prevent="publish"><h2>发布 Python 模板</h2><p>场景描述将同时参与 BM25 与向量检索，发布后源码以当前版本快照执行。</p><label>模板名称 *<input v-model="publishForm.templateName" required></label><label>场景描述 *<textarea v-model="publishForm.scenario" required placeholder="说明适用业务场景和用户可能提出的问题"></textarea></label><label>功能描述 *<textarea v-model="publishForm.description" required></textarea></label><div class="ds-form-row"><label>关键词<input v-model="publishForm.keywords"></label><label>所属领域<input v-model="publishForm.domain"></label></div><div class="ds-form-row"><label>输入 Schema<textarea v-model="publishForm.inputSchema"></textarea></label><label>输出 Schema<textarea v-model="publishForm.outputSchema"></textarea></label></div><footer><button type="button" @click="publishOpen=false">取消</button><button class="ds-primary" :disabled="busy">发布到 MCP</button></footer></form></div>
  </section>
</template>
<script src="../js/views/DataScienceView.js"></script>
<style src="../styles/pages/data-science.css"></style>
