<template>
  <section class="ds-page" :class="{'develop-mode':tab==='develop'}">
    <header class="ds-header">
      <div><span>能力管理 / 数据科学</span></div>
      <button class="ds-primary ds-header-action" @click="openAssetDialog">＋ 添加 Python 环境</button>
    </header>
    <nav class="ds-tabs"><button v-for="item in tabs" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id">{{ item.label }}</button></nav>
    <p v-if="error" class="ds-alert error">{{ error }}</p><p v-if="message&&tab!=='develop'" class="ds-alert success">{{ message }}</p>

    <div v-if="loading" class="ds-empty">正在加载数据科学工作台…</div>
    <section v-show="!loading&&tab==='environment'" class="ds-environment-pane">
      <div v-if="!assets.length" class="ds-empty"><strong>当前没有可用的数据科学环境</strong><p>请先添加 Python 环境。只有 READY 环境才允许创建、运行和发布脚本。</p><button class="ds-primary" @click="openAssetDialog">添加环境</button></div>
      <template v-else><div class="ds-list-toolbar"><label class="ds-list-search"><span>⌕</span><input v-model.trim="environmentQuery" placeholder="检索环境名称、描述或状态"></label><span>共 {{ filteredEnvironmentAssets.length }} 个环境</span></div><div v-if="!filteredEnvironmentAssets.length" class="ds-empty"><strong>没有匹配的环境</strong><p>请调整检索关键词后重试。</p></div><div v-else class="ds-card-grid"><article v-for="asset in pagedEnvironmentAssets" :key="asset.id" class="ds-card ds-environment-card"><div class="ds-card-head"><div><span class="environment-eyebrow">数据科学环境</span><strong>{{ asset.name }}</strong></div><span :class="['ds-status', statusClass(asset.status)]">{{ assetStatusLabel(asset.status) }}</span></div><p>{{ asset.description || '用于 Python 数据分析、脚本调试与能力发布。' }}</p><div class="environment-capabilities"><span>Python {{ asset.pythonVersion || '3.11' }}</span><span>独立运行环境</span><span>支持开发、测试与发布</span></div><footer><span :class="['environment-dot',statusClass(asset.status)]"></span>{{ environmentStatusMessage(asset.status) }}</footer></article></div><nav v-if="filteredEnvironmentAssets.length" class="ds-pagination"><button :disabled="environmentCurrentPage<=1" @click="environmentPage=environmentCurrentPage-1">上一页</button><span>第 {{ environmentCurrentPage }} / {{ environmentPageCount }} 页</span><button :disabled="environmentCurrentPage>=environmentPageCount" @click="environmentPage=environmentCurrentPage+1">下一页</button></nav></template>
    </section>

    <div v-show="!loading&&tab==='develop'" class="ds-develop-pane">
      <div v-if="!readyAssets.length" class="ds-empty"><strong>开发入口已锁定</strong><p>当前用户没有 READY 状态的 Python Asset，请先发布并成功创建隔离环境。</p><button class="ds-primary" @click="tab='environment'">前往 Python 环境</button></div>
      <div v-else ref="workspace" class="ds-ide" :class="{'explorer-collapsed':!explorerOpen,'ai-collapsed':!aiOpen,fullscreen:isFullscreen}">
        <header class="ide-commandbar">
          <div class="ide-brand"><span class="python-mark">Py</span><div><strong>Python Studio</strong><small>安全隔离开发环境</small></div></div>
          <div class="ide-context"><label><span>运行环境</span><select v-model="form.assetId"><option v-for="asset in readyAssets" :value="asset.id" :key="asset.id">{{ asset.name }}</option></select></label><span class="ide-runtime"><i></i> Ready</span></div>
          <div class="ide-actions"><button title="Ctrl/Cmd + S" @click="save" :disabled="busy"><span>⌘S</span> 保存</button><button title="Ctrl/Cmd + Enter" @click="run" :disabled="busy||!form.id" class="run">{{ runState==='running'?'◌ 执行中…':'▶ 运行' }}</button><button class="publish" @click="publishOpen=true" :disabled="busy||!canPublish">发布为模板</button><button class="icon-button sidebar-toggle" :class="{active:explorerOpen}" :title="explorerOpen?'收起脚本栏':'展开脚本栏'" @click="toggleExplorer">☰</button><button class="expand-button" :title="isFullscreen?'退出沉浸编辑':'放大为沉浸编辑器'" @click="toggleFullscreen">{{ isFullscreen?'↙ 退出全屏':'⛶ 放大编辑' }}</button></div>
        </header>

        <aside class="ide-explorer">
          <div class="panel-heading"><div><small>WORKSPACE</small><strong>我的脚本</strong></div><span class="panel-heading-actions"><button title="收起脚本栏" @click="toggleExplorer">‹</button><button title="新建脚本" @click="newScript">＋</button></span></div>
          <div class="explorer-search"><span>⌕</span><input v-model="explorerQuery" placeholder="搜索脚本"></div>
          <div class="explorer-group"><span>⌄</span><strong>PYTHON ASSET</strong><small>{{ scripts.length }}</small></div>
          <div class="explorer-files">
            <button v-for="script in pagedExplorerScripts" :key="script.id" :class="{active:form.id===script.id}" @click="selectScript(script)"><span class="py-file">Py</span><span><strong>{{ script.fileName }}</strong><small>{{ script.title || '未命名脚本' }}</small></span><i :class="statusClass(script.status)"></i></button>
            <div v-if="!filteredScripts.length" class="explorer-empty">没有匹配的脚本</div>
          </div>
          <footer><span>◉ {{ readyAssets.length }} 个环境</span><nav class="explorer-pagination"><button :disabled="explorerCurrentPage<=1" title="上一页" @click="explorerPage=explorerCurrentPage-1">‹</button><span>{{ explorerCurrentPage }}/{{ explorerPageCount }}</span><button :disabled="explorerCurrentPage>=explorerPageCount" title="下一页" @click="explorerPage=explorerCurrentPage+1">›</button><button title="刷新" @click="load">↻</button></nav></footer>
        </aside>

        <main class="ide-main" :class="{'bottom-collapsed':!bottomOpen}">
          <div class="editor-tabs"><div class="editor-tab-strip"><div v-for="item in editorTabs" :key="item.key" class="editor-tab" :class="{active:item.key===activeEditorTabKey}" :title="item.form.fileName" @click="activateEditorTab(item)"><span class="py-file">Py</span><input v-if="item.key===activeEditorTabKey" v-model.trim="form.fileName" class="file-name-input" placeholder="analysis.py" title="编辑文件名，按 Enter 保存" @click.stop @keydown.enter.prevent="save" @keydown.esc.prevent="restoreFileName"><span v-else class="tab-name">{{ item.form.fileName || '未命名脚本' }}</span><i v-if="editorTabDirty(item)" title="文件名或代码有未保存修改"></i><button class="tab-close" title="关闭页签" @click.stop="closeEditorTab(item)">×</button></div><button class="new-tab" title="新建脚本页签" @click="newScript">＋</button></div><div class="editor-tools"><button @click="formatDocument">格式化</button><button @click="aiOpen=true">✦ AI 补全 <kbd>⌘K</kbd></button></div></div>
          <div class="editor-breadcrumb"><span>workspace</span><b>›</b><span>{{ form.fileName }}</span><b>›</b><strong>Python</strong></div>
          <div ref="codeEditor" class="monaco-host" aria-label="Python 脚本编辑器"></div>
          <section class="ide-bottom">
            <nav><button :class="{active:bottomOpen&&bottomTab==='console'}" @click="bottomTab='console';bottomOpen=true">运行日志 <em v-if="runState!=='idle'" :class="runState">●</em></button><button :class="{active:bottomOpen&&bottomTab==='parameters'}" @click="bottomTab='parameters';bottomOpen=true">运行参数</button><span></span><button v-if="bottomOpen&&bottomTab==='console'" title="清空" @click="clearConsole">清空</button><button class="bottom-toggle" :title="bottomOpen?'收起底部面板':'展开底部面板'" @click="toggleBottom">{{ bottomOpen?'⌄ 收起':'⌃ 展开' }}</button></nav>
            <div v-show="bottomOpen&&bottomTab==='console'" class="terminal"><div><b>Python Runtime</b><span :class="['run-state',runState]"><i></i>{{ runStateLabel }}</span><small v-if="runFeedback?.durationMs!=null">{{ runFeedback.durationMs }} ms</small><small v-if="runFeedback?.exitCode!=null">退出码 {{ runFeedback.exitCode }}</small></div><pre :class="{failed:runState==='failed'}">{{ consoleText || '$ 点击“运行”执行当前脚本，stdout / stderr 和执行状态会显示在这里。' }}</pre></div>
            <div v-show="bottomOpen&&bottomTab==='parameters'" class="parameter-editor">
              <header class="parameter-heading"><div><strong>运行参数与脚本交互规范</strong><small>这里只接受 JSON 对象；平台会将整个对象注入环境变量 <code>CHATCHAT_INPUT_JSON</code>。</small></div><div><button @click="useParameterExample">填入参数示例</button><button @click="insertParameterReaderExample">插入 Python 读取代码</button></div></header>
              <div class="parameter-contract"><div><b>① 运行参数 JSON</b><code>{ "file_path": "/data/input/sales.csv", "limit": 100 }</code></div><span>字段名一一对应 →</span><div><b>② Python 脚本</b><code>params = json.loads(os.environ.get("CHATCHAT_INPUT_JSON", "{}"))<br>file_path = params.get("file_path")<br>limit = int(params.get("limit", 100))</code></div><span>→</span><div><b>③ 输出分析结果</b><code>print(json.dumps(result, ensure_ascii=False))</code></div></div>
              <label class="parameter-input"><span>本次运行参数</span><textarea v-model="parametersText" spellcheck="false" placeholder='例如：{"file_path":"/data/input/example.csv","limit":100}'></textarea><small :class="['parameter-validation',{invalid:!parameterValidation.valid}]">{{ parameterValidation.valid?'✓':'!' }} {{ parameterValidation.text }}</small></label>
            </div>
          </section>
          <footer class="ide-statusbar"><span>⑂ main*</span><span>✓ 隔离策略已启用</span><span title="输入代码时自动显示，也可按 Ctrl+Space 手动触发">⌁ 自动补全 Ctrl+Space</span><i></i><span>Ln {{ cursorPosition.lineNumber }}, Col {{ cursorPosition.column }}</span><span>Spaces: 4</span><span>UTF-8</span><span>Python 3.11</span><span>{{ codeLines }} 行 · {{ codeChars }} 字符</span></footer>
        </main>

        <aside class="ai-panel">
          <header><div><span class="ai-orb">✦</span><div><strong>AI 编程助手</strong><small :title="selectedAiModelLabel">{{ aiBusy?'正在调用 '+selectedAiModelLabel:aiStage==='ready'?'代码建议已生成':aiStage==='applied'?'建议已写入编辑器':selectedAiModelLabel }}</small></div></div><button title="收起 AI 助手" @click="toggleAi">›</button></header>
          <section class="ai-body">
            <div v-if="aiBusy" class="ai-progress"><span class="ai-thinking">✦</span><strong>正在生成 Python 代码</strong><p>{{ selectedAiModelLabel }} · 已读取当前脚本 {{ codeLines }} 行{{ aiSelection?'及选中代码':'' }}</p><ol><li :class="{done:aiProgressStep>1,active:aiProgressStep===1}"><i></i>读取代码上下文</li><li :class="{done:aiProgressStep>2,active:aiProgressStep===2}"><i></i>分析提示词意图</li><li :class="{done:aiProgressStep>3,active:aiProgressStep===3}"><i></i>调用所选模型生成代码</li><li :class="{done:aiProgressStep===4}"><i></i>等待结果返回</li></ol></div>
            <template v-else-if="!aiSuggestion"><div class="ai-intro"><span>✦</span><strong>想让代码做什么？</strong><p>描述需求，AI 会结合当前脚本和选中代码生成建议。</p></div><div class="ai-examples"><button v-for="example in aiExamples" :key="example" @click="useAiExample(example)">{{ example }}</button></div></template>
            <div v-else class="ai-result" :class="{applied:aiStage==='applied'}"><div><strong>{{ aiStage==='applied'?'代码已写入':'代码建议已生成' }}</strong><span :title="aiSuggestion.modelName">{{ aiSuggestion.modelName || selectedAiModelLabel }} · {{ aiSuggestionLines }} 行 · {{ aiElapsedMs }} ms</span></div><p v-if="aiAppliedInfo" class="ai-applied-notice"><b>✓ 已{{ aiAppliedInfo.verb }}{{ aiAppliedInfo.mode }}</b><span>{{ aiAppliedInfo.lines }} 行代码已写入并选中，当前修改尚未保存。</span></p><pre>{{ aiSuggestion.code }}</pre><footer><button @click="resetAiSuggestion">{{ aiStage==='applied'?'继续生成':'放弃' }}</button><button class="apply" :class="{done:aiStage==='applied'}" :disabled="aiStage==='applied'" @click="applyAiSuggestion">{{ aiStage==='applied'?'✓ 已应用':aiApplyLabel }}</button></footer></div>
          </section>
          <footer class="ai-composer"><div class="ai-composer-options"><select v-model="aiAction" :disabled="aiBusy"><option value="generate">生成</option><option value="continue">续写</option><option value="fix">修复</option><option value="optimize">优化</option></select><select v-model="aiModel" class="ai-model-select" :disabled="aiBusy||!aiModels.length" title="代码生成模型"><option v-if="!aiModels.length" value="">暂无可用模型</option><option v-for="model in aiModels" :key="model.value" :value="model.value">{{ model.label }}{{ model.defaultModel?'（默认）':'' }}</option></select></div><textarea ref="aiPrompt" v-model.trim="aiPrompt" :disabled="aiBusy" placeholder="例如：读取 values 数组，计算均值、中位数和标准差…" @keydown.ctrl.enter.prevent="askAi" @keydown.meta.enter.prevent="askAi"></textarea><div><small>{{ aiBusy?'AI 正在读取并生成代码…':'Ctrl + Enter 发送' }}</small><button @click="askAi" :disabled="aiBusy||!aiPrompt||!aiModel">{{ aiBusy?'生成中…':'发送 ↑' }}</button></div></footer>
        </aside>
      </div>
    </div>

    <section v-show="!loading&&tab==='data'" class="ds-data-pane">
      <div class="ds-pane-title"><div><h2>我的数据</h2><p>管理 Python 分析使用的数据文件；传输到 MCP 后可在沙箱中只读访问。</p></div><button class="ds-primary" @click="openDataUpload">＋ 上传数据</button></div>
      <div class="ds-list-toolbar"><label class="ds-list-search"><span>⌕</span><input v-model.trim="dataQuery" placeholder="搜索文件名称、类型或状态"></label><span>共 {{ filteredDataFiles.length }} 个文件</span></div>
      <div v-if="!dataFiles.length" class="ds-empty"><strong>还没有分析数据</strong><p>上传 CSV、XLS、XLSX、JSON、TXT、LOG、PARQUET、ORC 或 ZIP 文件后，Python 脚本即可读取。</p><button class="ds-primary" @click="openDataUpload">上传第一个文件</button></div>
      <div v-else-if="!filteredDataFiles.length" class="ds-empty"><strong>没有匹配的数据文件</strong></div>
      <div v-else class="ds-table-wrap"><table><thead><tr><th>文件名称</th><th>类型</th><th>大小</th><th>状态</th><th>Python 路径</th><th>上传时间</th><th>操作</th></tr></thead><tbody><tr v-for="file in pagedDataFiles" :key="file.id"><td><strong>{{ file.fileName }}</strong><small>{{ file.purpose || '未填写用途' }}</small></td><td>{{ file.fileType }}</td><td>{{ formatBytes(file.fileSize) }}</td><td><span :class="['ds-status',statusClass(file.status)]">{{ dataStatusLabel(file.status) }}</span></td><td><code class="data-path">{{ file.pythonPath }}</code></td><td>{{ formatTime(file.createdAt) }}</td><td class="data-actions"><button :disabled="file.status!=='AVAILABLE'" @click="copyDataPath(file)">复制路径</button><button :disabled="file.status!=='AVAILABLE'" @click="downloadData(file)">下载</button><button class="danger" @click="removeData(file)">删除</button></td></tr></tbody></table></div>
      <nav v-if="filteredDataFiles.length" class="ds-pagination"><button :disabled="dataCurrentPage<=1" @click="dataPage=dataCurrentPage-1">上一页</button><span>第 {{ dataCurrentPage }} / {{ dataPageCount }} 页</span><button :disabled="dataCurrentPage>=dataPageCount" @click="dataPage=dataCurrentPage+1">下一页</button></nav>
    </section>

    <div v-show="!loading&&tab==='scripts'" class="ds-scripts-pane"><div v-if="!scripts.length" class="ds-empty">暂无脚本</div><template v-else><div class="ds-list-toolbar"><label class="ds-list-search"><span>⌕</span><input v-model.trim="scriptCatalogQuery" placeholder="检索脚本名称、标题、环境或状态"></label><span>共 {{ filteredCatalogScripts.length }} 个脚本</span></div><div v-if="!filteredCatalogScripts.length" class="ds-empty"><strong>没有匹配的脚本</strong><p>请调整检索关键词后重试。</p></div><div v-else class="ds-table-wrap"><table><thead><tr><th>脚本</th><th>Asset</th><th>版本</th><th>状态</th><th>最后测试</th><th>更新时间</th></tr></thead><tbody><tr v-for="script in pagedCatalogScripts" :key="script.id" @dblclick="selectScript(script)"><td><strong>{{ script.fileName }}</strong><small>{{ script.title }}</small></td><td>{{ assetName(script.assetId) }}</td><td>v{{ script.currentVersion }}</td><td><span :class="['ds-status',statusClass(script.status)]">{{ script.status }}</span></td><td>{{ script.lastTestSucceeded ? '成功' : '未通过' }}</td><td>{{ formatTime(script.updatedAt) }}</td></tr></tbody></table></div><nav v-if="filteredCatalogScripts.length" class="ds-pagination"><button :disabled="scriptCatalogCurrentPage<=1" @click="scriptCatalogPage=scriptCatalogCurrentPage-1">上一页</button><span>第 {{ scriptCatalogCurrentPage }} / {{ scriptCatalogPageCount }} 页</span><button :disabled="scriptCatalogCurrentPage>=scriptCatalogPageCount" @click="scriptCatalogPage=scriptCatalogCurrentPage+1">下一页</button></nav></template></div>

    <div v-if="assetOpen" class="ds-modal" @mousedown.self="assetOpen=false"><form @submit.prevent="createAsset"><h2>添加 Python 运行环境</h2><p>只能选择 MCP 管理端已发布的环境；镜像和资源边界由 MCP 统一治理。</p><label>环境名称 *<input v-model="assetForm.name" required></label><label>环境描述<textarea v-model="assetForm.description"></textarea></label><label>MCP 已发布环境 *<select v-model="assetForm.environmentId" required><option disabled value="">请选择环境</option><option v-for="env in environmentCatalog" :key="env.id" :value="env.id">{{ env.name }} · Python {{ env.pythonVersion }} · v{{ env.versionNumber }}</option></select></label><div v-if="selectedEnvironment" class="ds-alert"><strong>{{ selectedEnvironment.dockerImage }}</strong><br>{{ selectedEnvironment.cpuLimit }} CPU / {{ selectedEnvironment.memoryLimit }} / 网络{{ selectedEnvironment.networkEnabled?'开启':'禁用' }} / 超时 {{ selectedEnvironment.timeoutSeconds }}s</div><p v-if="!environmentCatalog.length" class="ds-alert error">MCP 尚未发布 Python 环境，请先到 MCP 管理端的 Python 管理页面发布。</p><footer><button type="button" @click="assetOpen=false">取消</button><button class="ds-primary" :disabled="busy||!environmentCatalog.length">{{ busy?'添加中…':'添加环境' }}</button></footer></form></div>
    <div v-if="dataUploadOpen" class="ds-modal" @mousedown.self="dataUploadOpen=false"><form @submit.prevent="uploadData"><h2>上传数据</h2><p>文件将通过 AES-GCM 加密传输到 MCP，并以只读卷挂载到 Python 沙箱。</p><label class="data-drop" @dragover.prevent @drop.prevent="dropDataFile"><input type="file" accept=".csv,.xls,.xlsx,.json,.txt,.log,.parquet,.orc,.zip" @change="chooseDataFile"><strong>{{ dataUploadFile?.name || '拖拽文件到此处，或点击选择文件' }}</strong><small>支持 CSV、XLS、XLSX、JSON、TXT、LOG、PARQUET、ORC、ZIP，最大 50 MB</small></label><label>数据用途（可选）<textarea v-model="dataUploadForm.purpose" placeholder="例如：客户交易数据，用于交易行为分析"></textarea></label><label>保留期限<select v-model="dataUploadForm.retention"><option value="PERMANENT">永久保留</option><option value="7_DAYS">7 天</option><option value="30_DAYS">30 天</option></select></label><footer><button type="button" @click="dataUploadOpen=false">取消</button><button class="ds-primary" :disabled="busy||!dataUploadFile">{{ busy?'加密传输中…':'上传' }}</button></footer></form></div>
    <div v-if="publishOpen" class="ds-modal" @mousedown.self="publishOpen=false"><form @submit.prevent="publish"><h2>发布 Python 模板</h2><p>场景描述将同时参与 BM25 与向量检索，发布后源码以当前版本快照执行。</p><label>模板名称 *<input v-model="publishForm.templateName" required></label><label>场景描述 *<textarea v-model="publishForm.scenario" required placeholder="说明适用业务场景和用户可能提出的问题"></textarea></label><label>功能描述 *<textarea v-model="publishForm.description" required></textarea></label><div class="ds-form-row"><label>关键词<input v-model="publishForm.keywords"></label><label>所属领域<input v-model="publishForm.domain"></label></div><div class="ds-form-row"><label>输入 Schema<textarea v-model="publishForm.inputSchema"></textarea></label><label>输出 Schema<textarea v-model="publishForm.outputSchema"></textarea></label></div><footer><button type="button" @click="publishOpen=false">取消</button><button class="ds-primary" :disabled="busy">发布到 MCP</button></footer></form></div>
  </section>
</template>
<script src="../js/views/DataScienceView.js"></script>
<style src="../styles/pages/data-science.css"></style>
