package com.chatchat.agents.runtime.event;

public enum AgentRunEventType {
    RUN_SUBMITTED,
    RUN_STARTED,
    STEP_RECORDED,
    OBSERVATION_RECORDED,
    BUSINESS_TEMPLATE_REQUIREMENT_MATCHING,
    CONFIRMATION_REQUIRED,
    RUN_COMPLETED,
    RUN_CANCELLED,
    RUN_FAILED
}
