create table agent_api_token (
    id varchar(64) not null,
    tenant_id varchar(64) not null,
    user_id varchar(64) not null,
    username varchar(64) not null,
    display_name varchar(128) not null,
    token_name varchar(128) not null,
    token_hash varchar(64) not null,
    token_preview varchar(32) not null,
    status varchar(32) not null,
    expires_at datetime(6),
    last_used_at datetime(6),
    last_used_ip varchar(128),
    last_used_path varchar(512),
    used_count bigint not null default 0,
    created_by varchar(64) not null,
    created_by_name varchar(128) not null,
    revoked_at datetime(6),
    revoked_by varchar(64),
    rotated_at datetime(6),
    created_at datetime(6) not null,
    updated_at datetime(6) not null,
    primary key (id),
    unique key uk_agent_api_token_hash (token_hash),
    key idx_agent_api_token_user (tenant_id, user_id),
    key idx_agent_api_token_status (status, expires_at)
) engine=InnoDB;
