create table knowledge_ir_unit (
    id bigint not null auto_increment,
    knowledge_id varchar(160) not null,
    document_id varchar(160) not null,
    tenant_id varchar(100) not null,
    owner_user_id varchar(100),
    visibility varchar(20),
    permission_roles text,
    tags_json text,
    version varchar(80),
    domain varchar(200),
    knowledge_type varchar(40) not null,
    title varchar(500),
    semantic_description text,
    rules_json text,
    constraints_json text,
    applicable_intents_json text,
    required_inputs_json text,
    compact_representation text not null,
    search_text text not null,
    source_id varchar(200),
    source_chunk_id varchar(200),
    source_document_name varchar(500),
    source_section varchar(500),
    source_citation text,
    relevance double,
    active bit default 1,
    created_at bigint,
    updated_at bigint,
    primary key (id),
    unique key uk_knowledge_ir_doc_unit (document_id, knowledge_id),
    key idx_knowledge_ir_document (document_id, active),
    key idx_knowledge_ir_tenant_type (tenant_id, knowledge_type, active)
) engine=InnoDB;

